version: '3.4'

services:
  identity-service:
    container_name: superbad-store.identity.api
    image: phuc1403/superbad-store.identity:dev
    ports:
      - "5003:80"
      - "50051:50051"
    build:
      context: .
      dockerfile: Services/Identity/Presentation/IdentityManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Identity; Username=postgres; Password=password
      - ConnectionStrings__Redis=superbad-store.redis
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - Kestrel__Endpoints__Http__Url=http://+:80
      - Kestrel__Endpoints__gRPC__Url=http://+:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq:5341
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
      order-service:
        condition: service_started
    links:
      - db
  order-service:
    container_name: superbad-store.order.api
    image: phuc1403/superbad-store.order:dev
    ports:
      - "5005:80"
    build:
      context: .
      dockerfile: Services/Order/Presentation/OrderManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Order; Username=postgres; Password=password
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - ConnectionStrings__Redis=superbad-store.redis
      - GrpcUrls__Identity=http://superbad-store.identity.api:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq.:5341
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    links:
      - db
      - rabbitmq
  db:
    container_name: superbad-store.db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/opt/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 0s
      retries: 5
  redis:
    container_name: superbad-store.redis
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 0s
      retries: 5
  rabbitmq:
    container_name: superbad-store.rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 0s
      retries: 5
  seq:
    container_name: superbad-store.seq
    image: datalust/seq:latest
    ports:
      - "8080:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
volumes:
  data: