version: '3.4'

services:
  api-gateway:
    container_name: superbad-store.api-gateway
    image: phuc1403/superbad-store.api-gateway:dev
    ports:
      - "3000:80"
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - Routes__0__DownstreamHostAndPorts__0__Host=superbad-store.identity.api
      - Routes__0__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__0__Config__0__Url=http://superbad-store.identity.api/swagger/v1/swagger.json
      - Routes__1__DownstreamHostAndPorts__0__Host=superbad-store.inventory.api
      - Routes__1__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__1__Config__0__Url=http://superbad-store.inventory.api/swagger/v1/swagger.json
      - Routes__2__DownstreamHostAndPorts__0__Host=superbad-store.shopping.api
      - Routes__2__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__2__Config__0__Url=http://superbad-store.shopping.api/swagger/v1/swagger.json
      - Routes__3__DownstreamHostAndPorts__0__Host=superbad-store.shared.api
      - Routes__3__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__3__Config__0__Url=http://superbad-store.shared.api/swagger/v1/swagger.json
      - Routes__4__DownstreamHostAndPorts__0__Host=superbad-store.order.api
      - Routes__4__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__4__Config__0__Url=http://superbad-store.order.api/swagger/v1/swagger.json
      - Routes__5__DownstreamHostAndPorts__0__Host=superbad-store.review.api
      - Routes__5__DownstreamHostAndPorts__0__Port=80
      - SwaggerEndPoints__5__Config__0__Url=http://superbad-store.review.api/swagger/v1/swagger.json
    depends_on:
      - identity-service
      - inventory-service
      - shopping-service
      - order-service
      - shared-service
      - review-service
    links:
      - identity-service
      - inventory-service
      - shopping-service
      - order-service
      - shared-service
      - review-service
  identity-service:
    container_name: superbad-store.identity.api
    image: phuc1403/superbad-store.identity:dev
    ports:
      - "5003:80"
      - "50051:50051"
    build:
      context: .
      dockerfile: Services/Identity/Presentation/IdentityManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Identity; Username=postgres; Password=password
      - ConnectionStrings__Redis=superbad-store.redis
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - Kestrel__Endpoints__Http__Url=http://+:80
      - Kestrel__Endpoints__gRPC__Url=http://+:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq:5341
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
      inventory-service:
        condition: service_started
      order-service:
        condition: service_started
      review-service:
        condition: service_started
    links:
      - db
  inventory-service:
    container_name: superbad-store.inventory.api
    image: phuc1403/superbad-store.inventory:dev
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: Services/Inventory/Presentation/InventoryManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Inventory; Username=postgres; Password=password
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - ConnectionStrings__Redis=superbad-store.redis
      - GrpcUrls__Identity=http://superbad-store.identity.api:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq.:5341
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    links:
      - db
      - rabbitmq
  review-service:
    container_name: superbad-store.review.api
    image: phuc1403/superbad-store.review:dev
    ports:
      - "5006:80"
    build:
      context: .
      dockerfile: Services/Review/Presentation/ReviewManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Review; Username=postgres; Password=password
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - ConnectionStrings__Redis=superbad-store.redis
      - GrpcUrls__Identity=http://superbad-store.identity.api:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq.:5341
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    links:
      - db
      - rabbitmq
  order-service:
    container_name: superbad-store.order.api
    image: phuc1403/superbad-store.order:dev
    ports:
      - "5005:80"
    build:
      context: .
      dockerfile: Services/Order/Presentation/OrderManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Order; Username=postgres; Password=password
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - ConnectionStrings__Redis=superbad-store.redis
      - GrpcUrls__Identity=http://superbad-store.identity.api:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq.:5341
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    links:
      - db
      - rabbitmq
  shopping-service:
    container_name: superbad-store.shopping.api
    image: phuc1403/superbad-store.shopping:dev
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: Services/Shopping/Presentation/ShoppingManagement.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgres=Host=superbad-store.db; Port=5432; Database=Shopping; Username=postgres; Password=password
      - ConnectionStrings__RabbitMQ=superbad-store.rabbitmq
      - ConnectionStrings__Redis=superbad-store.redis
      - GrpcUrls__Identity=http://superbad-store.identity.api:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq.:5341
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started
    links:
      - db
      - rabbitmq
  shared-service:
    container_name: superbad-store.shared.api
    image: phuc1403/superbad-store.shared:dev
    ports:
      - "5004:80"
    build:
      context: .
      dockerfile: Services/Shared/Presentations/Shared.Presentation.API/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Redis=superbad-store.redis
      - GrpcUrls__Identity=http://superbad-store.identity.api:50051
      - Serilog__SeqServerUrl=http://superbad-store.seq.:5341
      - CloudStorage__ConnectionString=
    depends_on:
      redis:
        condition: service_healthy
      seq:
        condition: service_started
  db:
    container_name: superbad-store.db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - data:/var/opt/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 0s
      retries: 5
  redis:
    container_name: superbad-store.redis
    image: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 10s
      timeout: 0s
      retries: 5
  rabbitmq:
    container_name: superbad-store.rabbitmq
    image: rabbitmq:3.12-management
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 0s
      retries: 5
  seq:
    container_name: superbad-store.seq
    image: datalust/seq:latest
    ports:
      - "8080:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
volumes:
  data: